# Описание сервисов
services:
  web:
    # Сборка контейнера из Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # Явное имя образа
    image: cosine_graph_generator:web
    # Команда для запуска
    command: python manage.py runserver 0.0.0.0:8000
    # Монтирование текущей директории
    volumes:
      - .:/app
    # Открытие порта
    ports:
      - "8000:8000"
    # Переменные окружения
    environment:
      - DEBUG=1